StadisticCalculator/Models/ExerciseParams.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StadisticCalculator.Models
{
    public class ExerciseParams
    {
        [Required(ErrorMessage = "Debes insertar los datos")]
        public string Numbers { get; set; }
        public int ClassInterval { get; set; }

        [Required(ErrorMessage = "Debes escribir el delimitador")]
        public char Delimiter { get; set; }
        public double Amplitude { get; set; }
        public double Range { get; set; }
        public List<string> Intervals { get; set; }
        public List<double> ClassMarks { get; set; }
        public List<double> AbsolutesFrequencies { get; set; }
        public List<double> RelativeFrequencies { get; set; }
        public List<double> TotalAcumulatedFrequencies { get; set; }
        public double ArithmeticMedia { get; set; }
        public double Median { get; set; }
        public double Fashion { get; set; }
        public double Variance { get; set; }
        public double StandardDesviation { get; set; }
        public double VariationCoefficent { get; set; }
        public bool HasArithmeticMedia { get; set; }
        public bool HasMedian { get; set; } 
        public bool HasFashion { get; set; }
        public bool HasVariance { get; set; }
        public bool HasStandardDesviation { get; set; }
        public bool HasVariationCoefficent { get; set; }
        public bool IsAscending { get; set; }

        public ExerciseParams()
        {
            Intervals = new List<string>();
            ClassMarks = new List<double>();
            AbsolutesFrequencies = new List<double>();
            RelativeFrequencies = new List<double>();
            TotalAcumulatedFrequencies = new List<double>();
            Delimiter = ',';

            ArithmeticMedia = 0;
            Median = 0;
            Fashion = 0;
            StandardDesviation = 0;
            Variance = 0;
            VariationCoefficent = 0;
        }
    }
}

StadisticCalculator/Models/General.cs
namespace StadisticCalculator.Models
{
    public class General
    {
        public string Numbers { get; set; }
        public int ClassInterval { get; set; }
        public char Delimiter { get; set; }
        public string[] NumbersArray { get; private set; }

        public General(string numbers)
        {
            Numbers = numbers;
            if(!string.IsNullOrEmpty(Numbers))
                NumbersArray = Numbers.Trim().Replace(Delimiter, ',').Split(',');
        }
    }
}

StadisticCalculator/Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using StadisticCalculator.Services;
using StadisticCalculator.Models;

namespace StadisticCalculator.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(ExerciseParams model)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    General general = new General(model.Numbers);

                    general.Delimiter = model.Delimiter;
                    general.ClassInterval = model.ClassInterval;

                    NumbersTools numbersTools = new NumbersTools(general);

                    Table table = new Table(general, numbersTools);
                    CentralTendencyMeasures centralTendencyMeasures = new CentralTendencyMeasures(general, table);

                    model.Range = table.GetRange();
                    model.Amplitude = table.GetAmplitude();
                    model.Intervals = table.GetIntervals();
                    model.ClassMarks = table.GetClassMark();
                    model.AbsolutesFrequencies = table.GetAbsolutesFrequency();
                    model.RelativeFrequencies = table.GetRelativeFrequencies();
                    model.TotalAcumulatedFrequencies = table.GetTotalAcumulatedFrequencies();


                    if (model.HasArithmeticMedia)
                        model.ArithmeticMedia = centralTendencyMeasures.GetArithmeticMedia();
                    if(model.HasMedian)
                        model.Median = centralTendencyMeasures.GetMedian();
                    if(model.HasFashion)
                        model.Fashion = centralTendencyMeasures.GetFashion();
                    if (model.HasVariance)
                        model.Variance = centralTendencyMeasures.GetVariance();
                    if (model.HasStandardDesviation)
                        model.StandardDesviation = centralTendencyMeasures.GetStandardDesviation();
                    if (model.HasVariationCoefficent)
                        model.VariationCoefficent = centralTendencyMeasures.GetVariationCoefficent();

                    ViewBag.Success = true;

                    return View(model);
                }
                else
                {
                    ViewBag.Error = "Ha ocurrido un error interno al generar la tabla, revisa si los datos proveídos son válidos";
                    return View();
                }
            }
            catch(Exception ex)
            {
                ViewBag.Success = false;
                ViewBag.Error = $"Ha ocurrido un error interno al generar la tabla: {ex.Message}";
                return View();
            }
        }

        public IActionResult How()
        {
            return View();
        }

    }
}

StadisticCalculator/Controllers/ToolsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using StadisticCalculator.Services;
using StadisticCalculator.Models;

namespace StadisticCalculator.Controllers
{
    public class ToolsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string numbers, char delimiter, bool isAscending)
        {
            try
            {
                General general = new General(numbers);
                general.Delimiter = delimiter;

                NumbersTools numbersTools = new NumbersTools(general);

                ViewBag.SortedNumbers = numbersTools.SortNumbers(isAscending);

                return View();
            }
            catch(Exception ex)
            {
                ViewBag.Error = $"Ha ocurrido un error interno al organizar los números: {ex.Message}";
                return View();
            }
        }

        public IActionResult FormatText()
        {
            return View();
        }

        [HttpPost]
        public IActionResult FormatText(string numbers, string option)
        {
            try
            {
                General general = new General(numbers);

                NumbersTools numbersTools = new NumbersTools(general);

                ViewBag.FormattedText = numbersTools.FormatNumbers(option);

                return View();
            }
            catch(Exception ex)
            {
                ViewBag.Error = $"Ha ocurrido un error interno al formatear el texto: {ex.Message}";
                return View();
            }
        }
    }
}

StadisticCalculator/Views/Home/Index.cshtml
@model StadisticCalculator.Models.ExerciseParams
@{
    ViewData["Title"] = "Generar tabla de frequencia";
}

<div class="container">
    <div class="row mt-4">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="text-center"><h3 class="uk-card-title">Generadora de tabla de frecuencia</h3></div>
            <div class="text-justify">
                Este apartado sirve para generar tablas de frecuencia, a partir de unos datos dados, aségurate de proveer los datos correctamente y como se indica en el formulario, y con esto podrás generar una tabla de frecuencia, que va a servir para resolver tus ejercicios de estadística. Está centrada a esas personas que ya saben hacer la tabla y quieren comprobar sus resultados y/o también para esas que quieren ahorrar procesos porque necesitan sacar otros datos aparte de la tabla.
            </div>
            <div class="text-center"><h3 class="uk-card-title">Ingresar Datos: </h3></div>
            <form asp-action="Index">
                <div class="form-group">
                    <label for="Numbers">Ingresa los números:</label>
                    <small class="text-white">Nota: Si son decimales, el separador decimal debe ser con ( . )</small>
                    <textarea id="Numbers" cols="30" rows="5" style="resize: none;" asp-for="Numbers" class="uk-textarea" required></textarea>
                    <p class="text-danger">@Html.ValidationMessageFor(m => m.Numbers)</p>
                </div>
                <div class="form-group">
                    <label for="ClassInterval">Ingresa el intervalo de clase (k): </label>
                    <small class="text-white">Nota: Si el ejercicio no te provee esta información coloca un 0</small>
                    <input type="number" id="ClassInterval" asp-for="ClassInterval" class="uk-input" required />
                </div>
                <div class="form-group">
                    <label for="Delimiter">Delimitador o separador de los números:</label>
                    <small class="text-white"> (ej: ; , o -)</small>
                    <input type="text" id="Delimiter" asp-for="Delimiter" class="uk-input" maxlength="1" required />
                    <p class="text-danger">@Html.ValidationMessageFor(m => m.Delimiter)</p>
                </div>
                <div class="form-check-inline">
                    <input type="checkbox" asp-for="HasArithmeticMedia" value="true" class="uk-checkbox"> &nbsp;
                    <label for="ArithmeticMedia">Calcular media aritmética</label>
                </div>
                <div class="form-check-inline">
                    <input type="checkbox" asp-for="HasMedian" value="true" class="uk-checkbox"> &nbsp;
                    <label for="Median">Calcular mediana</label>
                </div>
                <div class="form-check-inline">
                    <input type="checkbox" asp-for="HasFashion" value="true" class="uk-checkbox"> &nbsp;
                    <label for="Median">Calcular moda</label>
                </div>
                <div class="form-check-inline">
                    <input type="checkbox" asp-for="HasVariance" value="true" class="uk-checkbox"> &nbsp;
                    <label for="Fashion">Calcular varianza</label>
                </div>
                <div class="form-check-inline">
                    <input type="checkbox" asp-for="HasStandardDesviation" value="true" class="uk-checkbox"> &nbsp;
                    <label for="ArithmeticMedia">Calcular desviación estándar</label>
                </div>
                <div class="form-check-inline">
                    <input type="checkbox" asp-for="HasVariationCoefficent" value="true" class="uk-checkbox"> &nbsp;
                    <label for="Median">Calcular coeficiente de variación</label>
                </div>
                <div class="text-center">
                    <button type="submit" class="uk-button-primary btn-block">Generar tabla</button>
                </div>
                @if (ViewBag.Error != null)
                {
                    <p class="text-danger">@ViewBag.Error</p>
                }

            </form>
        </div>
        <div class="col-md-3"></div>
    </div>

    @if (ViewBag.Success != null && ViewBag.Success)
    {
        <div class="row mt-3">
            <div class="col-md-12">
                <div class="text-center"><h3 class="uk-card-title">Tabla generada:</h3></div>
                <table class="uk-table uk-table-hover">
                    <thead>
                        <tr>
                            <th style="color: #212529; font-weight: bold;">Intervalos</th>
                            <th style="color: #212529; font-weight: bold;">x<span style="font-size: 10px;">i</span></th>
                            <th style="color: #212529; font-weight: bold;">f<span style="font-size: 10px;">i</span></th>
                            <th style="color: #212529; font-weight: bold;">f<span style="font-size: 10px;">r</span></th>
                            <th style="color: #212529; font-weight: bold;">F</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Intervals.Count; i++)
                        {
                            <tr>
                                <td>@Model.Intervals[i]</td>
                                <td>@Model.ClassMarks[i]</td>
                                <td>@Model.AbsolutesFrequencies[i]</td>
                                <td>@Model.RelativeFrequencies[i]</td>
                                <td>@Model.TotalAcumulatedFrequencies[i]</td>
                            </tr>
                        }

                        <tr>
                            <td>Total</td>
                            <td></td>
                            <td>@Model.AbsolutesFrequencies.Sum()</td>
                            <td>@Math.Round(Model.RelativeFrequencies.Sum())</td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>

                @if (Model.ArithmeticMedia != 0)
                {
                    <p><span class="uk-text-bold">Media Aritmética:</span> @Model.ArithmeticMedia</p>
                }
                @if (Model.Median != 0)
                {
                    <p><span class="uk-text-bold">Mediana:</span> @Model.Median</p>
                }
                @if (Model.Fashion != 0)
                {
                    <p><span class="uk-text-bold">Moda:</span>@Model.Fashion</p>
                }
                @if (Model.Variance != 0)
                {
                    <p><span class="uk-text-bold">Varianza:</span> @Model.Variance</p>
                }
                @if (Model.StandardDesviation != 0)
                {
                    <p><span class="uk-text-bold">Desviación estándar:</span> @Model.StandardDesviation</p>
                }
                @if (Model.VariationCoefficent != 0)
                {
                    <p><span class="uk-text-bold">Coeficiente de variación:</span> @Model.VariationCoefficent</p>
                }
            </div>
        </div>
    }
</div>

StadisticCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frequency Table Generator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/uikit.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="~/icon.ico">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">

    <script src="~/js/uikit-icons.min.js"></script>

    <script data-ad-client="ca-pub-4742814454206688" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <meta name="google-site-verification" content="5U1z0fxWvekz8uM1bzC_In4v5bZ8Hlg-BFKctCJVhAM" />
</head>
<body style="background: #d9a11e;">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light uk-background-primary">
            <a asp-action="Index" asp-controller="Home" class="navbar-brand text-white">Frequency Table Generator</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-action="Index" asp-controller="Home">
                            Generar tabla de frecuencia
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-action="How" asp-controller="Home">¿Cómo se hace la tabla?</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-action="Index" asp-controller="Tools">Herramienta para ordenar números</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-action="FormatText" asp-controller="Tools">Herramienta para formatear números</a>
                    </li>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="page-footer font-small blue pt-4">
        <div class="container-fluid text-center text-md-left">
            <div class="row">
                <div class="col-md-6 mt-md-0 mt-3">
                    <h5 class="text-uppercase text-white">Frequency Table Generator</h5>
                    <p>
                        Esta página tiene el objetivo de generar automáticamente tabla de frecuencia a partir de datos dados.
                        Por favor, aségurate de usarla para comprobar tus resultados o para ahorrarte tiempo si ya sabes cómo hacerla.
                        En caso de no saber cómo hacerla, te recomiendo mi <a asp-controller="Home" asp-action="How">guía</a>
                        de cómo hacerla.
                    </p>

                </div>
                <hr class="clearfix w-100 d-md-none pb-3">
                <div class="col-md-3 mb-md-0 mb-3">
                    <h5 class="text-uppercase text-white">Links</h5>

                    <ul class="list-unstyled">
                        <li>
                            <a asp-action="Index" asp-controller="Home">Generar tabla de frecuencia</a>
                        </li>
                        <li>
                            <a asp-action="How" asp-controller="How">¿Cómo se hace la tabla?</a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Tools">Herramienta para ordenar Números</a>
                        </li>
                        <li>
                            <a asp-action="FormatText" asp-controller="Tools">Herramienta para formatear números</a>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
        <div class="footer-copyright text-center py-3">
            <p>&copy; @DateTime.Now.Year Erlyn Emmanuel Taveras Villaman Copyright.</p>
            <p>¿Necesitas un sistema, aplicación o página web? Puedes contactarme al correo erlynetv@gmail.com</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/uikit.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

StadisticCalculator/Views/Tools/FormatText.cshtml
@{
    ViewData["Title"] = "Formatear texto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-4">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="text-center"><h3 class="uk-card-title">Herramienta para formatear texto: </h3></div>
            <div class="text-justify">
                <p>Con esta herramienta puedes formatear los números, si los números los copiaste de otros ejercicios de ejemplo y tienen formatos varios que se te hacen incómodo organizar y quitar espaciados y demás, esta herramienta es tu opción. Con esto puedes formatear los números por ejemplo si están separadas con tabulación (ej: 1     2) es un espacio grande, puedes seleccionar la opción tabulación y esto le quitará este espaciado. Si está separado por saltos de línea (ej: 1 <br /> 2) también puedes seleccionar esta opción para quitarla. Y por último, si tienen espacios puedes quitarle los espacios si así lo deseas seleccionando esa opción también.</p>
            </div>
            <div class="text-center"><h3 class="uk-card-title">Ingresar Datos: </h3></div>
            <form asp-action="FormatText">
                <div class="form-group">
                    <label for="Numbers">Ingresa los números:</label>
                    <small class="text-white">Nota: Si son decimales, el separador decimal debe ser con ( . )</small>
                    <textarea id="Numbers" cols="30" rows="5" style="resize: none;" name="numbers" class="uk-textarea" required></textarea>
                </div>
                <div class="form-group">
                    <label for="Options">¿Qué quieres quitar?: </label>
                    <select class="uk-select" name="option" id="Options">
                        <option value="tab">Tabulación</option>
                        <option value="breakline">Salto de línea</option>
                        <option value="space">Espaciado</option>
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="uk-button-primary btn-block">Formatear Texto</button>
                </div>
            </form>
            @if (ViewBag.Error != null)
            {
                <p class="text-danger">@ViewBag.Error</p>
            }
        </div>
        <div class="col-md-3"></div>
    </div>

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Numbers">Texto formateado: </label>
                @if (ViewBag.FormattedText != null)
                {
                    <textarea id="Numbers" cols="30" rows="5" style="resize: none;" class="uk-textarea" readonly>
@ViewBag.FormattedText
                    </textarea>
                }
                else
                {
                    <textarea id="Numbers" cols="30" rows="5" style="resize: none;" class="uk-textarea" readonly></textarea>
                }
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>

StadisticCalculator/Views/Tools/Index.cshtml
@model StadisticCalculator.Models.ExerciseParams
@{
    ViewData["Title"] = "Organizar números";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-4">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="text-center"><h3 class="uk-card-title">Herramienta para ordenar números: </h3></div>
            <div class="text-justify">
                <p>Con esta herramienta puedes organizar los números de menor a mayor o de mayor a menor, es una herramienta útil para tus ejercicios de estadística, ya que si tienes muchos datos se te hará difícil organizarlos tú mismo uno por uno, con esta herramienta obtienes resultados precisos y exactos.</p>
            </div>
            <div class="text-center"><h3 class="uk-card-title">Ingresar Datos: </h3></div>
            <form asp-action="Index">
                <div class="form-group">
                    <label for="Numbers">Ingresa los números:</label>
                    <small class="text-white">Nota: Si son decimales, el separador decimal debe ser con ( . )</small>
                    <textarea id="Numbers" cols="30" rows="5" style="resize: none;" asp-for="@Model.Numbers" class="uk-textarea" required></textarea>
                </div>
                <div class="form-group">
                    <label for="Delimiter">Delimitador o separador de los números:</label>
                    <small class="text-white"> (ej: ; , o -)</small>
                    <input type="text" id="Delimiter" asp-for="@Model.Delimiter" class="uk-input" maxlength="1" required />
                </div>
                <div class="form-check-inline">
                    <input type="radio" id="isAscending" asp-for="@Model.IsAscending" value="true" checked class="uk-radio"> &nbsp;
                    <label>Ordenar de forma ascendente</label>
                </div>
                <div class="form-check-inline">
                    <input type="radio" id="isAscending" asp-for="@Model.IsAscending" value="false" class="uk-radio"> &nbsp;
                    <label>Ordenar de forma descendente</label>
                </div>
                <div class="text-center">
                    <button type="submit" class="uk-button-primary btn-block">Ordenar números</button>
                </div>
            </form>
            @if (ViewBag.Error != null)
            {
                <p class="text-danger">@ViewBag.Error</p>
            }
        </div>
        <div class="col-md-3"></div>
    </div>

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Numbers">Números ordenados: </label>
                @if (ViewBag.SortedNumbers != null)
                {
                    <textarea id="Numbers" cols="30" rows="5" style="resize: none;" class="uk-textarea" required>
@ViewBag.SortedNumbers
                    </textarea>
                }
                else
                {
                    <textarea id="Numbers" cols="30" rows="5" style="resize: none;" class="uk-textarea" required></textarea>
                }
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>